import pandas as pd
import os

# Define paths
BASE_DIR = '/Users/y.aykut/Codebase/Machine Learning IU/'
INPUT_PATH = os.path.join(BASE_DIR, 'data/processed/ptbxl_merged_labeled.csv')
OUTPUT_PATH = os.path.join(BASE_DIR, 'data/processed/ptbxl_cleaned_columns.csv')

def main():
    print("Loading data...")
    df = pd.read_csv(INPUT_PATH, index_col='ecg_id')
    
    # List of sparse/metadata columns to drop
    # These are either >50% missing or administrative/noise flags
    cols_to_drop = [
        'height', 'weight', 'nurse', 'site', 
        'infarction_stadium1', 'infarction_stadium2', 
        'validated_by', 'baseline_drift', 'static_noise', 
        'burst_noise', 'electrodes_problems', 'extra_beats', 
        'pacemaker', 'initial_autogenerated_report', 'validated_by_human'
    ]
    
    # Check which ones actually exist in the df
    existing_cols_to_drop = [c for c in cols_to_drop if c in df.columns]
    
    print(f"Dropping {len(existing_cols_to_drop)} sparse/metadata columns:")
    print(existing_cols_to_drop)
    
    df_dropped = df.drop(columns=existing_cols_to_drop)
    
    # Now find missing values in the remaining columns
    missing_counts = df_dropped.isnull().sum()
    missing_counts = missing_counts[missing_counts > 0]
    
    print("\n" + "="*50)
    print("REMAINING COLUMNS WITH MISSING VALUES")
    print("="*50)
    
    ecg_features_missing = []
    other_missing = []
    
    for col, count in missing_counts.items():
        ratio = (count / len(df_dropped)) * 100
        info = f"{col}: {count} missing ({ratio:.2f}%)"
        
        # Heuristic to identify ECG features (usually contain underscores and CamelCase parts like P_On, QRS, etc.)
        # or are part of the known 12SL feature set
        if any(x in col for x in ['_Global', '_Lead', '_I', '_II', '_III', '_aVR', '_aVL', '_aVF', '_V1', '_V2', '_V3', '_V4', '_V5', '_V6']):
            ecg_features_missing.append(info)
        else:
            other_missing.append(info)
            
    print(f"\n--- ECG Features ({len(ecg_features_missing)}) ---")
    for item in ecg_features_missing:
        print(item)
        
    print(f"\n--- Other/Clinical Features ({len(other_missing)}) ---")
    for item in other_missing:
        print(item)
        
    # Save the cleaned dataframe
    print(f"\nSaving cleaned data to {OUTPUT_PATH}...")
    df_dropped.to_csv(OUTPUT_PATH)
    print("Done.")

if __name__ == "__main__":
    main()
